version: 2
registries:
  git-github-com:
    type: git
    url: https://github.com
    username: c-access-token
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - stefthoen
  ignore:
  - dependency-name: gatsby-image
    versions:
    - 2.10.0
    - 2.8.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
    - 2.8.1
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.7.1
    - 3.9.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.11.0
    - 2.9.1
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.11.2
    - 2.13.4
  - dependency-name: gatsby
    versions:
    - 2.29.3
    - 2.31.1
  - dependency-name: gatsby-plugin-styled-components
    versions:
    - 3.7.0
    - 3.9.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.11.0
    - 2.9.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.7.0
    - 3.9.0
  registries:
  - git-github-com
